import { useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'motion/react'
import { ArrowRight, BadgeCheck, CalendarClock, Check, ChevronDown, CircleDollarSign, Headphones, Menu, Mic2, PhoneCall, Route, ShieldCheck, Sparkles, Users, WalletCards, X } from 'lucide-react'

const nav = [['For riders','riders'],['For drivers','drivers'],['Fares','fares'],['Safety','safety'],['AUATON','auaton']]
const stats = [['0%','Commission on every trip'],['₦2,500','Current published base fare'],['3 min','Free waiting time'],['24/7','Safety line']]
const fares = [
  ['Base fare','₦2,500'],['Per kilometre','₦150'],['Per minute','₦50'],['Waiting','₦100/min after 3 free min'],['Trip insurance','₦300'],['State road fund','₦30']
]
const faqs = [
  ['Does MyKaab charge drivers commission?','No. MyKaab uses a subscription model instead of taking a percentage of every journey.'],
  ['How are fares calculated?','The published structure includes a base fare, distance, time, waiting after the first three free minutes, trip insurance and a state road fund. The app shows the applicable itemised fare before booking.'],
  ['Can a rider and driver agree on another fare?','Yes. MyKaab allows a rider and driver to agree a different price before the trip begins.'],
  ['How does MyKaab verify drivers?','Drivers submit identity, licence and vehicle information. Union membership is verified by the relevant AUATON chapter where applicable.'],
  ['What happens during an emergency?','The product includes one-tap SOS and a 24/7 safety line. The exact in-app response flow will be shown when the apps launch.'],
  ['Does MyKaab expose my phone number?','No. Private, masked communication is designed to keep personal phone numbers hidden.'],
  ["What is AUATON's role?",'AUATON determines and verifies its own membership. MyKaab uses that verification as part of driver eligibility where applicable.'],
  ['Where can I download the MyKaab app?','The Rider and Driver apps are in final testing. Join early access to be notified when genuine store links are available.'],
  ['Are MyKaab fares fixed?','Published rates may change, and riders and drivers can agree another fare before a trip. The rate shown in the app before booking is the applicable rate.']
]

function Logo({light=false}) { return <a href="#top" className="logo" aria-label="MyKaab home"><span className="logo-mark">M</span><span className={light?'text-white':''}>MyKaab</span></a> }

function Navbar() {
  const [open,setOpen] = useState(false)
  const [scrolled,setScrolled] = useState(false)
  useEffect(()=>{ const fn=()=>setScrolled(scrollY>24); fn(); addEventListener('scroll',fn,{passive:true}); return()=>removeEventListener('scroll',fn)},[])
  return <header className={`navbar ${scrolled?'nav-scrolled':''}`}>
    <div className="nav-inner"><Logo />
      <nav className="nav-links" aria-label="Main navigation">{nav.map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>
      <div className="nav-actions"><a className="signin" href="#early-access">Portal sign in</a><a className="btn btn-gold btn-small" href="#early-access">Get early access</a><button className="menu-btn" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-label="Open navigation">{open?<X/>:<Menu/>}</button></div>
    </div>
    <AnimatePresence>{open&&<motion.nav initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} className="mobile-menu">{nav.map(([label,id])=><a key={id} onClick={()=>setOpen(false)} href={`#${id}`}>{label}<ArrowRight size={18}/></a>)}<a href="#early-access">Portal sign in<ArrowRight size={18}/></a></motion.nav>}</AnimatePresence>
  </header>
}

function FareReceipt({compact=false,total=5855}) { return <div className={`receipt ${compact?'receipt-compact':''}`}>
  <div className="receipt-head"><span>YOUR ESTIMATED FARE</span><span className="live-dot">Illustrative</span></div>
  <div className="receipt-route"><span className="route-dot gold"></span><div><small>Pickup</small><b>Marina, Lagos Island</b></div></div>
  <div className="receipt-route"><span className="route-dot navy"></span><div><small>Destination</small><b>Yaba, Lagos</b></div></div>
  <div className="receipt-lines"><div><span>Base fare</span><b>₦2,500</b></div><div><span>Distance + time</span><b>₦3,025</b></div><div><span>Insurance + road fund</span><b>₦330</b></div></div>
  <div className="receipt-total"><span>Estimated total</span><strong>₦{total.toLocaleString()}</strong></div>
</div> }

function PhoneMockup({driver=false}) { return <div className={`phone ${driver?'driver-phone':''}`} aria-label={`${driver?'Driver':'Rider'} app illustrative preview`}><div className="phone-bar"><span></span><b>9:41</b><span>●●</span></div><div className="phone-screen">
  <div className="mini-brand"><span className="mini-mark">M</span><span>{driver?'Driver':'Rider'}</span><BadgeCheck size={15}/></div>
  {driver ? <><p className="phone-kicker">TODAY'S EARNINGS</p><h3>₦28,450</h3><div className="earnings-chart"><i/><i/><i/><i/><i/><i/><i/></div><div className="trip-done"><div><Check size={16}/></div><span><small>Trip completed</small><b>Ikeja → Victoria Island</b></span></div><div className="driver-total"><span>Passenger paid</span><b>₦6,780</b><span>Platform commission</span><b className="zero">₦0</b><strong>You receive</strong><strong>₦6,450</strong></div></> : <><div className="map-ui"><svg viewBox="0 0 260 220" role="img" aria-label="Illustrative Lagos route map"><path d="M-10 65C60 120 80 35 150 80s55 95 130 66"/><path d="M20 210c20-55 60-63 90-112s50-58 145-85"/><path className="route-line" d="M38 176c26-30 52-26 72-64s55-24 87-68"/><circle cx="38" cy="176" r="7"/><circle cx="197" cy="44" r="8"/></svg><div className="eta-chip">4 min away</div></div><div className="ride-sheet"><span className="sheet-handle"></span><small>CHOOSE YOUR RIDE</small><div className="ride-row"><span className="car-icon">K</span><span><b>Kaab Go</b><small>Comfortable everyday rides</small></span><strong>₦5,855</strong></div><button>Confirm pickup</button></div></>}
</div></div> }

function Hero() { return <section id="top" className="hero"><div className="hero-grid"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.65}} className="hero-copy"><h1>Ride with Nigeria.<br/><em>Earn with Nigeria.</em></h1><p>Know what your trip costs before you book. Drivers keep the fare they earn. One transparent platform, built for both sides of every trip.</p><div className="hero-actions"><a className="btn btn-gold" href="#early-access">Book a ride <ArrowRight size={18}/></a><a className="btn btn-outline" href="#drivers">Drive with us</a></div></motion.div>
  <motion.div initial={{opacity:0,y:34}} animate={{opacity:1,y:0}} transition={{duration:.7,delay:.12}} className="hero-visual"><div className="map-grid"></div><svg className="hero-route" viewBox="0 0 600 620"><path d="M28 510C165 430 82 270 245 250s145-180 324-194"/></svg><div className="phone-wrap"><PhoneMockup/></div><motion.div initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} transition={{delay:.45}} className="floating-receipt"><FareReceipt compact/></motion.div><div className="commission-badge"><strong>0%</strong><span>driver<br/>commission</span></div></motion.div></div></section> }

function Stats(){return <section className="stats"><div className="stats-grid">{stats.map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section>}

function Difference(){return <section className="section cream" id="riders"><div className="section-head"><div><p className="eyebrow">Built differently</p><h2>A ride platform designed for both sides of the trip.</h2></div><p>Most mobility platforms are built around the transaction. MyKaab is designed around the people making the trip happen.</p></div><div className="difference-grid">
  <article className="feature-card feature-large"><span className="card-num">01</span><div><p className="eyebrow">For drivers</p><h3>Zero commission. Not a reduced commission—none.</h3><p>MyKaab uses a subscription model instead of taking a percentage of every journey.</p></div><div className="money-flow"><div><span>Trip fare</span><b>₦8,400</b></div><ArrowRight/><div><span>You receive</span><b>₦8,400</b></div></div></article>
  <article className="feature-card"><span className="card-num">02</span><div><p className="eyebrow">For riders</p><h3>Transparent before you move.</h3><p>See what makes up the fare before confirming.</p></div><div className="mini-receipt">{fares.slice(0,3).map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></article>
  <article className="feature-card dark-card"><span className="card-num">03</span><div><p className="eyebrow">With AUATON</p><h3>Built with the union.</h3><p>Driver identity and membership work with AUATON rather than bypassing the union.</p></div><div className="union-id"><span>AUATON MEMBER</span><BadgeCheck/><b>Chapter verified</b></div></article>
</div></section>}

function Rider(){const [show,setShow]=useState(false); return <section className="section rider-section"><div className="rider-layout"><div><p className="eyebrow">For riders</p><h2>Know the price before you get in.</h2><p className="lead">MyKaab itemises your fare before you book, so you can see the journey—not guess at the number.</p><div className="principles">{[['01','An itemised fare'],['02','Agree a price'],['03','Help when you need it']].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></div><div className="booking-card"><div className="booking-top"><span>Plan a ride</span><b>Illustrative booking</b></div><label><small>PICKUP</small><span>Marina, Lagos Island</span></label><label><small>DESTINATION</small><span>Herbert Macaulay Way, Yaba</span></label><div className="booking-options"><button className="active">Ride now</button><button><CalendarClock size={16}/> Schedule</button></div><button className="btn btn-navy full" onClick={()=>setShow(v=>!v)}>{show?'Hide estimate':'See estimated fare'}<ArrowRight size={18}/></button><AnimatePresence>{show&&<motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0,height:0}}><FareReceipt compact/></motion.div>}</AnimatePresence></div></div></section>}

function FareCalculator(){const [km,setKm]=useState(12),[mins,setMins]=useState(28),[wait,setWait]=useState(4); const total=useMemo(()=>2500+km*150+mins*50+Math.max(0,wait-3)*100+300+30,[km,mins,wait]);return <section className="section fare-section" id="fares"><div className="fare-layout"><div><p className="eyebrow">No surprises</p><h2>A fare you can actually understand.</h2><p className="lead">Every charge is listed before you confirm and itemised again after the trip.</p><div className="rate-list">{fares.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div><p className="disclaimer">Rates may change. The current rate shown in the app before booking is the applicable rate.</p></div><div className="calculator"><div className="calc-head"><div><small>FARE SIMULATOR</small><h3>Illustrative estimate</h3></div><CircleDollarSign/></div><div className="calc-fields"><label>Distance <span>{km} km</span><input type="range" min="1" max="35" value={km} onChange={e=>setKm(+e.target.value)}/></label><label>Trip duration <span>{mins} min</span><input type="range" min="5" max="90" value={mins} onChange={e=>setMins(+e.target.value)}/></label><label>Waiting time <span>{wait} min</span><input type="range" min="0" max="20" value={wait} onChange={e=>setWait(+e.target.value)}/></label></div><div className="calc-total"><span>Illustrative estimate</span><motion.strong key={total} initial={{opacity:.5,y:5}} animate={{opacity:1,y:0}}>₦{total.toLocaleString()}</motion.strong></div><p>This is not a live booking quote.</p></div></div></section>}

function Drivers(){return <section className="section driver-section" id="drivers"><div className="driver-grid"><div className="driver-copy"><p className="eyebrow gold-text">For drivers</p><h2>The fare is yours.<br/>All of it.</h2><div className="zero-type"><strong>0%</strong><span>platform<br/>commission</span></div><p>MyKaab charges a subscription instead of taking a percentage of every journey. Approved drivers may also choose relevant benefits; only benefits selected by the driver create deductions.</p><div className="driver-features">{[['No commission, ever',WalletCards],['Cover you choose',ShieldCheck],['Earnings you can check',CircleDollarSign]].map(([t,I])=><div key={t}><I/><span>{t}</span></div>)}</div></div><div className="driver-visual"><img src="/driver-lagos.png" alt="Illustrative editorial image of a Nigerian driver checking a phone beside a dark sedan in Lagos"/><div className="driver-phone-float"><PhoneMockup driver/></div></div></div></section>}

function DriverStory(){return <section className="story-section"><div className="story-inner"><p className="eyebrow">One journey. Two people.</p><h2>The people moving Nigeria should be able to see where their money goes.</h2><div className="story-steps">{[['TRIP 01','Fare received','₦8,400'],['TRIP 02','Deductions explained','Item by item'],['TRIP 03','Earnings retained','Commission ₦0']].map((x,i)=><article key={x[0]}><span>{x[0]}</span><div className="step-icon">{i+1}</div><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>}

function Union(){const steps=['Driver applies','Driver declares union membership','Chapter officer verifies membership','MyKaab confirms eligibility'];return <section className="section union-section" id="auaton"><div className="union-grid"><div><p className="eyebrow">Built with AUATON</p><h2>Built with the union.<br/>Not around it.</h2><p className="lead">AUATON determines its own membership. MyKaab uses verified union identity as part of a clearer, more accountable driver journey where applicable.</p><blockquote>“Union membership is verified—not issued—by MyKaab.”</blockquote></div><div className="verify-flow">{steps.map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span><div><small>{i===2?'AUATON STEP':'MYKAAB STEP'}</small><b>{s}</b></div>{i<steps.length-1&&<i/>}</div>)}</div></div></section>}

function Safety(){const cards=[{title:'Verified before the first trip',text:'Identity, driver licence and vehicle information are checked before a driver begins.',icon:BadgeCheck,big:true},{title:'Your number stays private',text:'Masked calling keeps personal phone numbers out of the conversation.',icon:PhoneCall},{title:'One tap for help',text:'SOS access and a 24/7 safety line stay close during a trip.',icon:ShieldCheck},{title:'Trip recording',text:'In-app trip recordings may be retained for up to 30 days, in line with the currently published information.',icon:Mic2},{title:'Share your trip',text:'Keep trusted people connected to your journey.',icon:Users}];return <section className="section safety-section" id="safety"><div className="section-head"><div><p className="eyebrow">Safety</p><h2>Both of you are accounted for.</h2></div><p>Safety tools are designed for the rider and the person behind the wheel.</p></div><div className="safety-grid">{cards.map(({title,text,icon:Icon,big})=><article className={big?'safety-big':''} key={title}><Icon/><div>{big&&<div className="profile-chip"><span>AO</span><div><b>Ademola Okafor</b><small><Check size={12}/> Identity & vehicle verified</small></div></div>}<h3>{title}</h3><p>{text}</p></div></article>)}</div></section>}

function HowItWorks(){const [tab,setTab]=useState('rider');const data={rider:['Enter your destination','Check your itemised fare','Choose your ride','Travel and stay connected'],driver:['Apply','Submit verification documents','Complete union verification where applicable','Start receiving trips','Track exactly what you earn']};return <section className="section how-section"><div className="how-head"><div><p className="eyebrow">How it works</p><h2>From ready to moving.</h2></div><div className="tabs" role="tablist"><button role="tab" aria-selected={tab==='rider'} onClick={()=>setTab('rider')}>Rider</button><button role="tab" aria-selected={tab==='driver'} onClick={()=>setTab('driver')}>Driver</button></div></div><div className="how-grid"><AnimatePresence mode="wait"><motion.div key={tab} initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-18}} className="how-steps">{data[tab].map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span><p>{s}</p></div>)}</motion.div></AnimatePresence><div className="how-phone"><PhoneMockup driver={tab==='driver'}/></div></div></section>}

function EarlyAccess(){const [type,setType]=useState('rider'); const [state,setState]=useState('idle'); function submit(e){e.preventDefault(); if(!e.currentTarget.checkValidity()){setState('error'); return} setState('loading'); setTimeout(()=>setState('success'),850)} return <section className="section access-section" id="early-access"><div className="access-card"><div className="access-intro"><p className="eyebrow">Early access</p><h2>One platform.<br/>Two apps.<br/>Built for Nigeria.</h2><p>Both apps are in final testing. Join the list for launch updates—no fake store links, just a useful message when the apps are ready.</p><div className="app-pills"><span>MyKaab Rider <small>Final testing</small></span><span>MyKaab Driver <small>Final testing</small></span></div></div><div className="form-wrap">{state==='success'?<motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} className="success-state"><div><Check/></div><h3>You're on the early access list.</h3><p>We'll use the details you provided only to share relevant MyKaab launch updates.</p><button onClick={()=>setState('idle')}>Add another person</button></motion.div>:<form onSubmit={submit} noValidate><fieldset><legend>I am a</legend><div className="choice"><button type="button" className={type==='rider'?'active':''} onClick={()=>setType('rider')}>Rider</button><button type="button" className={type==='driver'?'active':''} onClick={()=>setType('driver')}>Driver</button></div></fieldset><label>Name<input required name="name" placeholder="Your full name"/></label><div className="field-row"><label>Phone<input required name="phone" type="tel" placeholder="0800 000 0000"/></label><label>Email<input required name="email" type="email" placeholder="you@example.com"/></label></div><label>City<input required name="city" placeholder="Lagos"/></label>{type==='driver'&&<label>Vehicle type <span>(optional)</span><input name="vehicle" placeholder="e.g. Sedan"/></label>}{state==='error'&&<p className="form-error">Please complete the required fields with valid details.</p>}<button className="btn btn-gold full" disabled={state==='loading'}>{state==='loading'?'Joining…':'Join early access'}<ArrowRight size={18}/></button><small>Illustrative form — submissions are not connected to a live backend yet.</small></form>}</div></div></section>}

function FAQ(){const [open,setOpen]=useState(0);return <section className="section faq-section"><div className="faq-layout"><div><p className="eyebrow">Questions, answered</p><h2>The useful details.</h2><p>Clear answers based on MyKaab's currently published information.</p></div><div className="accordion">{faqs.map(([q,a],i)=><div className="faq" key={q}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><span>{q}</span><ChevronDown className={open===i?'rotate':''}/></button><AnimatePresence initial={false}>{open===i&&<motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}><p>{a}</p></motion.div>}</AnimatePresence></div>)}</div></div></section>}

function Footer(){return <footer><div className="footer-top"><div><Logo light/><h2>Ride with Nigeria.<br/><em>Earn with Nigeria.</em></h2><a href="#early-access" className="btn btn-gold">Get early access<ArrowRight size={18}/></a></div><div className="footer-cols"><div><b>Riders</b><a href="#riders">How it works</a><a href="#fares">Fares</a><a href="#safety">Safety</a></div><div><b>Drivers</b><a href="#drivers">Drive with MyKaab</a><a href="#drivers">Driver benefits</a><a href="#auaton">AUATON</a></div><div><b>Company</b><a href="#top">About</a><a href="#early-access">Contact</a><a href="#early-access">Support</a></div><div><b>Account</b><a href="#early-access">Portal sign-in</a><a href="#early-access">Privacy</a><a href="#early-access">Terms</a></div></div></div><div className="footer-bottom"><span>© 2026 MyKaab.</span><span>Operated with AUATON.</span><span>Built in Nigeria.</span></div></footer>}

function ScrollReveals(){useEffect(()=>{const targets=document.querySelectorAll('.section-head,.stats-grid>div,.difference-grid>.feature-card,.rider-layout>*,.fare-layout>*,.driver-copy>*,.driver-visual,.story-inner>*,.story-steps>*,.union-grid>*,.safety-grid>*,.how-head>*,.how-grid>*,.access-card>*,.faq-layout>*,footer .footer-top>*');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -30px'});targets.forEach((el,i)=>{el.classList.add('reveal-on-scroll');el.style.setProperty('--reveal-delay',`${Math.min(i%4,3)*75}ms`);observer.observe(el)});return()=>observer.disconnect()},[]);return null}

export default function App(){return <><ScrollReveals/><Navbar/><main><Hero/><Stats/><Difference/><Rider/><FareCalculator/><Drivers/><DriverStory/><Union/><Safety/><HowItWorks/><EarlyAccess/><FAQ/></main><Footer/><a href="#early-access" className="mobile-sticky">Get early access <ArrowRight size={17}/></a></>}
