import { useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'motion/react'
import { ArrowRight, BadgeCheck, CalendarClock, Check, ChevronDown, CircleDollarSign, Headphones, Menu, Mic2, Moon, PhoneCall, Route, ShieldCheck, Sparkles, Sun, Users, WalletCards, X } from 'lucide-react'

const nav = [['For riders','riders'],['For drivers','drivers'],['Fares','fares'],['Safety','safety'],['AUATON','auaton']]
const stats = [['0%','Commission on every trip'],['₦2,500','Current published base fare'],['3 min','Free waiting time'],['24/7','Safety desk']]
const fares = [
  ['Base fare','₦2,500','Charged once, at the start of every trip'],['Per kilometre','₦150–₦250','Illustrative city-based range'],['Per minute','₦50','Every minute from pickup to destination'],['Waiting','₦100/min','After three free minutes at pickup'],['Trip insurance','₦300','Passenger cover on every trip · levy'],['State road fund','₦30','Statutory contribution per trip · levy']
]
const faqs = [
  ['Does MyKaab charge drivers commission?','No. MyKaab runs on a flat subscription, not a cut of each trip. The driver keeps the trip fare.'],
  ['How is my fare calculated?','The example uses a ₦2,500 base fare, a city-selected per-kilometre rate between ₦150 and ₦250, ₦50 per minute and ₦100 per minute of waiting after the first three free minutes. Trip insurance is ₦300 and the state road fund is ₦30. City rates shown here are illustrative; confirm live rates in the app before booking.'],
  ['Can we agree on another price?','Yes. A rider and driver can settle a different fare before the trip starts. The agreed figure replaces the quote.'],
  ['How are drivers checked?','Driver licence and vehicle papers are checked before a driver takes a trip, and again when those papers expire. An AUATON chapter officer confirms a driver’s union membership.'],
  ['What happens if I need help?','The trip screen has an SOS button that reaches the MyKaab safety desk around the clock and, if selected, your emergency contact.'],
  ['Are my phone number and trip recording private?','Calls go through a number that belongs to neither the rider nor driver. Trip recordings are kept for thirty days, then deleted.'],
  ['What is AUATON’s role?','MyKaab operates the technology with AUATON. The union retains authority over its own membership; only a chapter officer can confirm a member.'],
  ['How do I request early access?','The Rider and Driver apps are in final testing. Email hello@mykaab.com.ng to request access.'],
  ['What happens to trip levies?','Trip insurance and the state road fund are passed on in full. They do not go to MyKaab.']
]

function Logo({light=false}) { return <a href="#top" className="logo" aria-label="MyKaab home"><span className="logo-mark">M</span><span className={light?'text-white':''}>MyKaab</span></a> }

function Navbar() {
  const [open,setOpen] = useState(false)
  const [scrolled,setScrolled] = useState(false)
  const [theme,setTheme] = useState(()=>{
    try {
      const saved=localStorage.getItem('mykaab-theme')
      if(saved==='dark'||saved==='light') return saved
      return matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'
    } catch { return 'light' }
  })
  useEffect(()=>{ const fn=()=>setScrolled(scrollY>24); fn(); addEventListener('scroll',fn,{passive:true}); return()=>removeEventListener('scroll',fn)},[])
  useEffect(()=>{
    document.documentElement.dataset.theme=theme
    document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='dark'?'#0B1220':'#F8F5EF')
    try { localStorage.setItem('mykaab-theme',theme) } catch {}
  },[theme])
  return <header className={`navbar ${scrolled?'nav-scrolled':''}`}>
    <div className="nav-inner"><Logo />
      <nav className="nav-links" aria-label="Main navigation">{nav.map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>
      <div className="nav-actions"><button className="theme-toggle" type="button" onClick={()=>setTheme(v=>v==='dark'?'light':'dark')} aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`} aria-pressed={theme==='dark'} title={`Switch to ${theme==='dark'?'light':'dark'} mode`}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button><a className="signin" href="#early-access">Contact</a><a className="btn btn-gold btn-small" href="#early-access">Get early access</a><button className="menu-btn" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-label={open?'Close navigation':'Open navigation'}>{open?<X/>:<Menu/>}</button></div>
    </div>
    <AnimatePresence>{open&&<motion.nav initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} className="mobile-menu">{nav.map(([label,id])=><a key={id} onClick={()=>setOpen(false)} href={`#${id}`}>{label}<ArrowRight size={18}/></a>)}<a href="#early-access">Contact<ArrowRight size={18}/></a></motion.nav>}</AnimatePresence>
  </header>
}

function FareReceipt({compact=false,total=5580}) { return <div className={`receipt ${compact?'receipt-compact':''}`}>
  <div className="receipt-head"><span>FARE EXAMPLE</span><span className="live-dot">Illustrative</span></div>
  <div className="receipt-lines"><div><span>Base fare</span><b>₦2,500</b></div><div><span>10 km × ₦150</span><b>₦1,500</b></div><div><span>25 min × ₦50</span><b>₦1,250</b></div><div><span>Waiting (2 min free)</span><b>₦0</b></div><div><span>Trip insurance levy</span><b>₦300</b></div><div><span>State road fund levy</span><b>₦30</b></div></div>
  <div className="receipt-total"><span>You pay</span><strong>₦{total.toLocaleString()}</strong></div><div className="receipt-keep"><span>Driver keeps</span><b>₦5,250</b><span>MyKaab commission</span><b>₦0</b></div>
</div> }

function PhoneMockup({driver=false}) { return <div className={`phone ${driver?'driver-phone':''}`} aria-label={`${driver?'Driver':'Rider'} app illustrative preview`}><div className="phone-bar"><span></span><b>9:41</b><span>●●</span></div><div className="phone-screen">
  <div className="mini-brand"><span className="mini-mark">M</span><span>{driver?'Driver':'Rider'}</span><BadgeCheck size={15}/></div>
  {driver ? <><p className="phone-kicker">TODAY'S EARNINGS</p><h3>₦28,450</h3><div className="earnings-chart"><i/><i/><i/><i/><i/><i/><i/></div><div className="trip-done"><div><Check size={16}/></div><span><small>Trip completed</small><b>Ikeja → Victoria Island</b></span></div><div className="driver-total"><span>Passenger paid</span><b>₦6,780</b><span>Platform commission</span><b className="zero">₦0</b><strong>You receive</strong><strong>₦6,450</strong></div></> : <><div className="map-ui"><svg viewBox="0 0 260 220" role="img" aria-label="Illustrative Lagos route map"><path d="M-10 65C60 120 80 35 150 80s55 95 130 66"/><path d="M20 210c20-55 60-63 90-112s50-58 145-85"/><path className="route-line" d="M38 176c26-30 52-26 72-64s55-24 87-68"/><circle cx="38" cy="176" r="7"/><circle cx="197" cy="44" r="8"/></svg><div className="eta-chip">4 min away</div></div><div className="ride-sheet"><span className="sheet-handle"></span><small>CHOOSE YOUR RIDE</small><div className="ride-row"><span className="car-icon">K</span><span><b>Kaab Go</b><small>Comfortable everyday rides</small></span><strong>₦5,855</strong></div><button>Confirm pickup</button></div></>}
</div></div> }

function Hero() { return <section id="top" className="hero"><div className="hero-grid"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.65}} className="hero-copy"><h1>Ride with Nigeria.<br/><em>Earn with Nigeria.</em></h1><p>Every fare is itemised before you book, and <strong>the driver keeps all of it.</strong> Zero commission.</p><div className="hero-actions"><a className="btn btn-gold" href="#early-access">Get early access <ArrowRight size={18}/></a><a className="btn btn-outline" href="#drivers">Drive with MyKaab</a></div><p className="hero-union-note">Built and operated with <b>AUATON</b>, the Amalgamated Union of App-Based Transporters of Nigeria.</p></motion.div>
  <motion.div initial={{opacity:0,y:34}} animate={{opacity:1,y:0}} transition={{duration:.7,delay:.12}} className="hero-visual hero-photo-wrap"><img className="hero-photo" src="/hero-lagos-ride.png" alt="A rider meeting her driver beside a car on a Lagos street"/></motion.div></div></section> }

function Stats(){return <section className="stats"><div className="stats-grid">{stats.map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section>}

function Difference(){return <section className="section cream" id="riders"><div className="section-head"><div><p className="eyebrow">One trip, two people</p><h2>Nothing hidden from either side.</h2></div><p>Riders see the price before they get in. Drivers see what the rider paid and what reached them. The numbers match.</p></div><div className="difference-grid">
  <article className="feature-card feature-large"><span className="card-num">01</span><div><p className="eyebrow">For drivers</p><strong className="commission-spotlight">0%</strong><h3>Zero commission.</h3><p>MyKaab runs on one flat subscription, not a cut of your trips. What the passenger pays for the journey is yours.</p></div><div className="money-flow"><div><span>Passenger pays</span><b>Trip fare</b></div><ArrowRight/><div><span>Driver keeps</span><b>All of it</b></div></div></article>
  <article className="feature-card"><span className="card-num">02</span><div><p className="eyebrow">For riders</p><h3>An itemised quote.</h3><p>Base fare, distance, time and the two levies are listed before you confirm.</p></div><div className="mini-receipt">{fares.slice(0,3).map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></article>
  <article className="feature-card dark-card"><span className="card-num">03</span><div><p className="eyebrow">With AUATON</p><h3>The union keeps its authority.</h3><p>MyKaab runs the technology. AUATON decides who belongs to the union.</p></div><div className="union-id"><span>MEMBER ID FORMAT</span><BadgeCheck/><b>Confirmed by a chapter officer</b></div></article>
</div></section>}

function Rider(){return <section className="section rider-section"><div className="rider-layout"><div><p className="eyebrow">For riders</p><h2>If you ride, know the cost first.</h2><p className="lead">Book in a few taps and know the cost before you commit. Settle a different fare with your driver before the trip starts, and that agreed figure replaces the quote.</p><div className="principles">{[['01','An itemised quote'],['02','Agree your own price'],['03','Help from the trip screen']].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></div><div className="rider-photo-card"><img src="/rider-trip-lagos.png" alt="A rider arriving at her destination in Lagos"/></div></div></section>}

function FareCalculator(){const [city,setCity]=useState('Lagos'),[km,setKm]=useState(10),[mins,setMins]=useState(25),[wait,setWait]=useState(2);const cityRates={Abuja:200,Lagos:250,'Port Harcourt':200,Kano:150};const perKm=cityRates[city];const driverKeep=2500+km*perKm+mins*50+Math.max(0,wait-3)*100;const total=driverKeep+300+30;return <section className="section fare-section" id="fares"><div className="fare-layout"><div><p className="eyebrow">The whole rate card, in public</p><h2>Every line, out in the open.</h2><p className="lead">Your app shows each charge with its rate before you confirm. Check the bill instead of taking it on trust.</p><div className="rate-list">{fares.map(([a,b,detail])=><div key={a}><span><b>{a}</b><small>{detail}</small></span><strong>{b}</strong></div>)}</div><p className="disclaimer">Trip insurance and the state road fund are passed on in full; they do not go to MyKaab. Rates may be adjusted. The app shows the rate in force before you book.</p></div><div className="calculator"><div className="calc-head"><div><small>ILLUSTRATIVE FARE EXAMPLE</small><h3>Adjust the journey</h3></div><CircleDollarSign/></div><div className="calc-fields"><label>City example <span>₦{perKm}/km</span><select aria-label="Choose a city for the illustrative fare" value={city} onChange={e=>setCity(e.target.value)}>{Object.keys(cityRates).map(name=><option key={name} value={name}>{name}</option>)}</select></label><label>Distance <span>{km} km</span><input aria-label="Distance in kilometres" type="range" min="1" max="40" value={km} onChange={e=>setKm(+e.target.value)}/></label><label>Journey time <span>{mins} min</span><input aria-label="Journey time in minutes" type="range" min="5" max="120" step="5" value={mins} onChange={e=>setMins(+e.target.value)}/></label><label>Waiting at pickup <span>{wait} min</span><input aria-label="Waiting minutes" type="range" min="0" max="15" value={wait} onChange={e=>setWait(+e.target.value)}/></label></div><div className="calc-breakdown"><div><span>Trip fare</span><b>₦{driverKeep.toLocaleString()}</b></div><div><span>Trip insurance levy</span><b>₦300</b></div><div><span>State road fund levy</span><b>₦30</b></div><div className="calc-total"><span>You pay</span><motion.strong key={total} initial={{opacity:.5,y:5}} animate={{opacity:1,y:0}}>₦{total.toLocaleString()}</motion.strong></div><div className="calc-keep"><span>Driver keeps</span><b>₦{driverKeep.toLocaleString()}</b></div><div><span>MyKaab commission</span><b>₦0</b></div></div><p>Illustrative city rates only—not confirmed live rates or a booking quote.</p></div></div></section>}

function Drivers(){return <section className="section driver-section" id="drivers"><div className="driver-grid"><div className="driver-copy"><p className="eyebrow gold-text">For drivers</p><h2>Your car, your time,<br/>your fare.</h2><div className="zero-type"><strong>0%</strong><span>platform<br/>commission</span></div><p>MyKaab runs on one flat subscription, not a cut of your trips. What the passenger pays for the journey is yours. Approved drivers can choose health cover, life cover and a pension; only benefits you switch on are deducted.</p><div className="driver-features">{[['No commission, ever',WalletCards],['Health, life & pension by choice',ShieldCheck],['Earnings you can check',CircleDollarSign]].map(([t,I])=><div key={t}><I/><span>{t}</span></div>)}</div></div><div className="driver-visual"><img src="/driver-lagos.png" alt="A Nigerian driver beside his car in Lagos"/><div className="driver-photo-label">YOUR WORK. YOUR EARNINGS.</div></div></div></section>}

function DriverStory(){return <section className="story-section"><div className="story-inner"><p className="eyebrow">One journey. Two people.</p><h2>Both sides can see where the money goes.</h2><div className="story-steps">{[['01','Passenger fare','Itemised before you book'],['02','MyKaab commission','₦0'],['03','Driver receives','The trip fare']].map((x,i)=><article key={x[0]}><span>STEP {x[0]}</span><div className="step-icon">{i+1}</div><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>}

function Union(){const steps=['Driver declares union membership','A chapter officer confirms it','MyKaab checks the confirmed membership','The union retains authority over its members'];return <section className="section union-section" id="auaton"><div className="union-grid"><div><p className="eyebrow">Built and operated with AUATON</p><h2>Built with the union,<br/>not around it.</h2><p className="lead">MyKaab operates the technology with AUATON. The platform runs the technology; the union keeps authority over its own members.</p><div className="union-points"><div><b>The union decides its own roll</b><p>A driver declares membership, and only a chapter officer can confirm it. MyKaab never issues a union card.</p></div><div><b>An identity that can be checked</b><p>Member numbers combine the union, state and serial so an officer can verify the format.</p></div></div></div><div className="idcard-sample" role="img" aria-label="Sample AUATON membership number format, for illustration only"><div><span>AUATON</span><b>Member identity</b></div><strong><i>AUA</i><i>LA</i><i>004127</i></strong><small>Union&nbsp;&nbsp;&nbsp; State&nbsp;&nbsp;&nbsp; Serial</small><em>Sample format for illustration only</em></div></div></section>}

function Safety(){const cards=[{title:'Verified before the first trip',text:'Driver licence and vehicle papers are checked before a driver takes a trip, and again whenever those papers expire.',icon:BadgeCheck,big:true},{title:'Nobody keeps your number',text:'Calls between rider and driver go through a number that belongs to neither of you.',icon:PhoneCall},{title:'One tap for help',text:'The SOS button on the trip screen reaches the MyKaab safety desk around the clock and, if selected, your emergency contact.',icon:ShieldCheck},{title:'Trip recording',text:'Recordings are kept for thirty days, then deleted.',icon:Mic2},{title:'Share your trip',text:'Share your trip from the trip screen.',icon:Users}];return <section className="section safety-section" id="safety"><div className="section-head"><div><p className="eyebrow">Safety</p><h2>Both of you are accounted for.</h2></div><p>Safety on MyKaab protects the person in the back seat and the person at the wheel.</p></div><div className="safety-grid">{cards.map(({title,text,icon:Icon,big})=><article className={big?'safety-big':''} key={title}><Icon/><div>{big&&<div className="profile-chip"><span><ShieldCheck size={22}/></span><div><b>Driver documents</b><small><Check size={12}/> Checked before trips</small></div></div>}<h3>{title}</h3><p>{text}</p></div></article>)}</div></section>}

function HowItWorks(){const [tab,setTab]=useState('rider');const data={rider:['Book in a few taps','Review the itemised quote','Agree a different fare if you choose','Share your trip or raise an alarm'],driver:['Apply and submit your documents','Get your licence and vehicle papers checked','AUATON chapter officer confirms membership','See what the passenger paid and what reached you']};return <section className="section how-section"><div className="how-head"><div><p className="eyebrow">How it works</p><h2>From ready to moving.</h2></div><div className="tabs" role="tablist"><button role="tab" aria-selected={tab==='rider'} onClick={()=>setTab('rider')}>Rider</button><button role="tab" aria-selected={tab==='driver'} onClick={()=>setTab('driver')}>Driver</button></div></div><div className="how-grid"><AnimatePresence mode="wait"><motion.div key={tab} initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-18}} className="how-steps">{data[tab].map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span><p>{s}</p></div>)}</motion.div></AnimatePresence><div className="how-photo"><img src={tab==='driver'?'/driver-lagos.png':'/rider-trip-lagos.png'} alt={tab==='driver'?'A driver beside his car in Lagos':'A rider arriving at her destination in Lagos'}/><span>{tab==='driver'?'Your car, your time, your fare':'Every line before you book'}</span></div></div></section>}

function EarlyAccess(){return <section className="section access-section" id="early-access"><div className="access-card"><div className="access-intro"><p className="eyebrow">Early access</p><h2>Be among the first on the road.</h2><p>Both apps are in final testing. Tell us whether you want to ride or drive, and we will send your early access invitation.</p><p className="founder-contact">Email <a href="mailto:hello@mykaab.com.ng?subject=Early%20access">hello@mykaab.com.ng</a></p></div><div className="early-access-links"><a href="mailto:hello@mykaab.com.ng?subject=Early%20access%3A%20Rider"><span><b>MyKaab Rider</b><small>Book, track and pay</small></span><strong>Request access <ArrowRight size={17}/></strong></a><a href="mailto:hello@mykaab.com.ng?subject=Early%20access%3A%20Driver"><span><b>MyKaab Driver</b><small>Sign up, get verified, keep your fare</small></span><strong>Request access <ArrowRight size={17}/></strong></a></div></div></section>}

function FAQ(){const [open,setOpen]=useState(0);return <section className="section faq-section"><div className="faq-layout"><div><p className="eyebrow">Questions, answered</p><h2>The useful details.</h2><p>Clear answers based on MyKaab's currently published information.</p></div><div className="accordion">{faqs.map(([q,a],i)=><div className="faq" key={q}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><span>{q}</span><ChevronDown className={open===i?'rotate':''}/></button><AnimatePresence initial={false}>{open===i&&<motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}><p>{a}</p></motion.div>}</AnimatePresence></div>)}</div></div></section>}

function Footer(){return <footer><div className="footer-top"><div><Logo light/><h2>Ride with Nigeria.<br/><em>Earn with Nigeria.</em></h2><a href="#early-access" className="btn btn-gold">Get early access<ArrowRight size={18}/></a></div><div className="footer-cols"><div><b>Riders</b><a href="#riders">For riders</a><a href="#fares">Public rate card</a><a href="#safety">Safety</a></div><div><b>Drivers</b><a href="#drivers">For drivers</a><a href="#drivers">Driver benefits</a><a href="#auaton">AUATON</a></div><div><b>Company</b><a href="#top">About MyKaab</a><a href="#early-access">Early access</a><a href="mailto:hello@mykaab.com.ng">Contact</a></div></div></div><div className="footer-bottom"><span>© 2026 MyKaab.</span><span>Operated with AUATON.</span><span>Built in Nigeria.</span></div></footer>}

function ScrollReveals(){useEffect(()=>{const targets=document.querySelectorAll('.section-head,.stats-grid>div,.difference-grid>.feature-card,.rider-layout>*,.fare-layout>*,.driver-copy>*,.driver-visual,.story-inner>*,.story-steps>*,.union-grid>*,.safety-grid>*,.how-head>*,.how-grid>*,.access-card>*,.faq-layout>*,footer .footer-top>*');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -30px'});targets.forEach((el,i)=>{el.classList.add('reveal-on-scroll');el.style.setProperty('--reveal-delay',`${Math.min(i%4,3)*75}ms`);observer.observe(el)});return()=>observer.disconnect()},[]);return null}

export default function App(){return <><ScrollReveals/><Navbar/><main><Hero/><Stats/><Difference/><Rider/><FareCalculator/><Drivers/><DriverStory/><Union/><Safety/><HowItWorks/><EarlyAccess/><FAQ/></main><Footer/></>}
